animal/urls.py
from animal import views
from django.conf.urls import url


urlpatterns = [
    url(r'^search', views.animal_search, name='animal_search'),
    url(r'^select_specie$', views.select_specie_to_filter_breed_and_color, name='select_specie'),
    url(r'^new', views.animal_new, name='animal_new'),
    url(r'^view/(?P<animal_id>\d+)/$', views.animal_view, name='animal_view'),
    url(r'^edit/(?P<animal_id>\d+)/$', views.animal_update, name='animal_edit'),
]

client/urls.py
from client import views
from django.conf.urls import url


urlpatterns = [
    url(r'^new', views.client_new, name='client_new'),
    url(r'^view/(?P<client_id>\d+)/$', views.client_view, name='client_view'),
    url(r'^edit/(?P<client_id>\d+)/$', views.client_update, name='client_edit'),
    url(r'^list', views.client_list, name='client_list'),
    url(r'^(?P<client_id>\d+)/services/$', views.client_service_list, name='client_service_list'),
]

medvet/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from home.views import home, language_change, report


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='custom_user/sign_in.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='custom_user/password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='custom_user/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='custom_user/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='custom_user/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^settings/password/$',
        auth_views.PasswordChangeView.as_view(template_name='custom_user/password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='custom_user/password_change_done.html'),
        name='password_change_done'),

    url(r'^language/(?P<language_code>(?:(?:\w{2})|(?:\w{2}\-\w{2})))$', language_change, name='language_change'),
    url(r'^report/', report, name='report'),
    url(r'^animal/', include('animal.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^custom_user/', include('custom_user.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^service/', include('services.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField

from client.validation import validate_cpf


class Client(models.Model):
    """
    An instance of this class represents a customer.

    '__str__'		Returns the name.
    """
    name = models.CharField(_('Name'), max_length=255)
    rg = models.CharField(_('RG'), max_length=12, blank=True)
    cpf = models.CharField(_('CPF'), blank=True, max_length=15, validators=[validate_cpf])
    email = models.EmailField(_('E-mail'), blank=True, null=True)
    phone = models.CharField(_('Phone'), max_length=15, blank=True)
    cellphone = models.CharField(_('Cell Phone'), max_length=15, blank=True)
    zipcode = models.CharField(_('Zip Code'), max_length=9, blank=True)
    street = models.CharField(_('Address'), max_length=255, blank=True)
    street_complement = models.CharField(_('Complement'), max_length=255, blank=True)
    number = models.PositiveIntegerField(_('Number'), blank=True, null=True)
    district = models.CharField(_('District'), max_length=255, blank=True)
    city = models.CharField(_('City'), max_length=255, blank=True)
    state = models.CharField(_('State'), max_length=255, blank=True)
    country = CountryField(_('Country'), blank=True, default='BR')
    note = models.CharField(_('Note'), max_length=255, blank=True)

    def __str__(self):
        return self.name


class ClientContact(models.Model):
    """
    An instance of this class represents a contact of a customer.
    """
    client_name = models.ForeignKey(Client)
    name = models.CharField(_('Name'), max_length=255, blank=True)
    phone = models.CharField(_("Phone"), max_length=15, blank=True)
    cellphone = models.CharField(_('Cell Phone'), max_length=15, blank=True)

payment/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


ONE = '1x'
TWO = '2x'
THREE = '3x'
FOUR = '4x'
FIVE = '5x'
SIX = '6x'
PAYMENT_OPTIONS = (
    (ONE, '1x'),
    (TWO, '2x'),
    (THREE, '3x'),
    (FOUR, '4x'),
    (FIVE, '5x'),
    (SIX, '6x'),
)


class PaymentMethod(models.Model):
    """
    An instance of this class is a payment method.
    Registration of the payment method will be done via Django Admin.

    '__str__'		Returns the name.
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PaymentRegister(models.Model):
    """
    An instance of this class is the payment register of one or more services.
    """
    installment = models.CharField(max_length=2, choices=PAYMENT_OPTIONS, default=ONE)
    discount_or_increase = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    installment_value = models.DecimalField(max_digits=10, decimal_places=2)
    note = models.TextField(blank=True)


class Payment(models.Model):
    """
    Inline fields for the payment register.
    """
    payment_register = models.ForeignKey(PaymentRegister)
    payment_method = models.ForeignKey(PaymentMethod)
    date = models.DateField()

client/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import Select, Textarea, TextInput
from django.utils.translation import ugettext_lazy as _

from client.models import Client, ClientContact


class ClientForm(forms.ModelForm):

    def __init__(self, data=None, *args, **kwargs):
        super(ClientForm, self).__init__(data, *args, **kwargs)
        self.fields['zipcode'].widget.attrs['onBlur'] = 'pesquisacep(this.value);'

    class Meta:
        model = Client
        fields = '__all__'

        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'required': "",
                                     'data-error': _('This field must be filled.')}),
            'rg': TextInput(attrs={'class': 'form-control'}),
            'cpf': TextInput(attrs={'class': 'form-control'}),
            'email': TextInput(attrs={
                'class': 'form-control', 'type': 'email', 'data-error': _('Incorrect e-mail'),
                'pattern': '^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$'}),
            'phone': TextInput(attrs={'class': 'form-control telephone_number', 'pattern': '^[- ()0-9]+'}),
            'cellphone': TextInput(attrs={'class': 'form-control telephone_number', 'pattern': '^[- ()0-9]+'}),
            'zipcode': TextInput(attrs={'class': 'form-control'}),
            'street': TextInput(attrs={'class': 'form-control'}),
            'street_complement': TextInput(attrs={'class': 'form-control'}),
            'number': TextInput(attrs={'class': 'form-control'}),
            'district': TextInput(attrs={'class': 'form-control'}),
            'city': TextInput(attrs={'class': 'form-control'}),
            'state': TextInput(attrs={'class': 'form-control'}),
            'country': Select(attrs={'class': 'form-control'}),
            'note': Textarea(attrs={'class': 'form-control', 'rows': '4'}),
        }


class ClientContactForm(forms.ModelForm):

    class Meta:
        model = ClientContact
        fields = ['name', 'phone', 'cellphone']

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'phone': TextInput(attrs={'class': 'form-control telephone_number', 'pattern': '^[- ()0-9]+'}),
            'cellphone': TextInput(attrs={'class': 'form-control telephone_number', 'pattern': '^[- ()0-9]+'}),
        }

client/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.db.models.deletion import ProtectedError
from django.forms.models import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.translation import ugettext as _

from client.models import Client, ClientContact
from client.forms import ClientForm, ClientContactForm
from configuration.models import Page
from services.models import Service
from services.filters import ServiceFilter


@login_required
def client_new(request, template_name="client/client_new.html"):
    client_form = ClientForm(request.POST or None)
    contact_inlineformset = inlineformset_factory(Client, ClientContact, form=ClientContactForm, extra=1)

    if request.method == "POST":
        if request.POST['action'] == "save":

            if client_form.is_valid():
                client = client_form.save(commit=False)
                client.save()

                contacts = contact_inlineformset(request.POST, instance=client)
                if contacts.is_valid():
                    contacts.save()

                messages.success(request, _('Customer created successfully.'))
                redirect_url = reverse("client_view", args=(client.id,))
                return HttpResponseRedirect(redirect_url)

            else:
                messages.warning(request, _('Information not saved.'))

        else:
            messages.warning(request, _('Action not available.'))

    context = {"client_form": client_form,
               "contact_inlineformset": contact_inlineformset,
               "creating": True}

    return render(request, template_name, context)


@login_required
def client_view(request, client_id, template_name="client/client_tabs.html"):
    client = get_object_or_404(Client, pk=client_id)
    client_form = ClientForm(request.POST or None, instance=client)
    contact_inlineformset = inlineformset_factory(Client, ClientContact, form=ClientContactForm, extra=1)
    contact_inlineformset = contact_inlineformset(instance=client)

    for field in client_form.fields:
        client_form.fields[field].widget.attrs['disabled'] = True

    for form in contact_inlineformset:
        for field in form.fields:
            form.fields[field].widget.attrs['disabled'] = True

    if request.method == "POST":
        if request.POST['action'] == "remove":

            try:
                client.delete()
                messages.success(request, _('Customer removed successfully.'))
                return redirect('client_list')
            except ProtectedError:
                messages.error(request, _("Error trying to delete the client."))
                redirect_url = reverse("client_view", args=(client_id,))
                return HttpResponseRedirect(redirect_url)

    context = {"viewing": True,
               "client": client,
               "client_form": client_form,
               "contact_inlineformset": contact_inlineformset,
               "tab": "1"
               }

    return render(request, template_name, context)


@login_required
def client_update(request, client_id, template_name="client/client_tabs.html"):
    client = get_object_or_404(Client, pk=client_id)
    client_form = ClientForm(request.POST or None, instance=client)
    contact_inlineformset = inlineformset_factory(Client, ClientContact, form=ClientContactForm, extra=1)
    contacts = contact_inlineformset(request.POST, instance=client)

    if request.method == "POST":
        if request.POST['action'] == "save":
            if client_form.is_valid() and contacts.is_valid():

                if client_form.has_changed():
                    client_form.save()

                if contacts.has_changed():
                    contacts.save()

                if client_form.has_changed() or contacts.has_changed():
                    messages.success(request, _('Customer updated successfully.'))
                else:
                    messages.warning(request, _('There is no changes to save.'))

                redirect_url = reverse("client_view", args=(client.id,))
                return HttpResponseRedirect(redirect_url)

    else:
        contact_inlineformset = contact_inlineformset(instance=client)

    context = {"client": client,
               "client_form": client_form,
               "contact_inlineformset": contact_inlineformset,
               "editing": True,
               "tab": "1"}

    return render(request, template_name, context)


@login_required
def client_list(request, template_name="client/list.html"):
    list_of_clients = Client.objects.all().order_by('name')
    page = request.GET.get('page', 1)

    try:
        get_number = Page.objects.get()
        paginator = Paginator(list_of_clients, get_number.pagination)
    except Page.DoesNotExist:
        get_number = 10
        paginator = Paginator(list_of_clients, get_number)

    try:
        clients = paginator.page(page)
    except PageNotAnInteger:
        clients = paginator.page(1)
    except EmptyPage:
        clients = paginator.page(paginator.num_pages)

    context = {'clients': clients}

    return render(request, template_name, context)


@login_required
def client_service_list(request, client_id, template_name="client/client_tabs.html"):
    client = get_object_or_404(Client, pk=client_id)
    service_list = Service.objects.filter(animal__owner=client).order_by('-date', '-id')
    services = ServiceFilter(request.GET, queryset=service_list)

    if request.method == "POST":
        if request.POST['action'] == "pay":
            services_selected = request.POST.getlist('services')
            if not services_selected:
                messages.error(request, _('You should select at least one service'))
            else:
                services_selected = '-'.join(str(service) for service in services_selected)
                redirect_url = reverse("payment_new", args=(services_selected,))
                return HttpResponseRedirect(redirect_url)

    context = {
        "client": client,
        "services": services,
        "tab": "2"
    }

    return render(request, template_name, context)

client/templates/client/client.html
{% load i18n staticfiles %}

<form id="form_id" role="form" method="post">{% csrf_token %}
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Name" %} <b style="color: red;">*</b></label>
                {{ client_form.name }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Email" %}</label>
                {{ client_form.email }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Phone" %}</label>
                {{ client_form.phone }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Cellphone" %}</label>
                {{ client_form.cellphone }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Security ID" %}</label>
                {{ client_form.cpf }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "National ID card" %}</label>
                {{ client_form.rg }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Zipcode" %}</label>
                {{ client_form.zipcode }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Street" %}</label>
                {{ client_form.street }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Number" %}</label>
                {{ client_form.number }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Street complement" %}</label>
                {{ client_form.street_complement }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "District" %}</label>
                {{ client_form.district }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "City" %}</label>
                {{ client_form.city }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "State" %}</label>
                {{ client_form.state }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Country" %}</label>
                {{ client_form.country }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Note" %}</label>
                {{ client_form.note }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>

    <div class="span6 offset3 well ">
        <div class="row">
            <div class="col-12">
                <label>
                    <h4>{% trans "Contacts" %}</h4>
                </label>
            </div>
        </div>

        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label>{% trans "Name" %}</label>
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label>{% trans "Phone" %}</label>
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label>{% trans "Cellphone" %}</label>
                </div>
            </div>
            <div class="col-2">
                <div class="form-group text-center">
                    <label>{% trans "Delete" %}</label>
                </div>
            </div>
        </div>

        {{ contact_inlineformset.management_form }}
        {% for contact in contact_inlineformset %}
            {% for hidden in contact.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <div class="input-group  input-group-sm">
                            <span class="input-group-addon"> <span class="glyphicon glyphicon-user"></span></span>
                            {{ contact.name }}
                        </div>
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        <div class="input-group  input-group-sm">
                            <span class="input-group-addon"> <span class="glyphicon glyphicon-earphone"></span></span>
                            {{ contact.phone }}
                        </div>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        <div class="input-group  input-group-sm">
                            <span class="input-group-addon"> <span class="glyphicon glyphicon-phone"></span></span>
                            {{ contact.cellphone }}
                        </div>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="form-group">
                        <div class="text-center">
                            {{ contact.DELETE }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% if creating %}
        <button type="submit" name="action" value="save" class="btn btn-primary">{% trans "Save" %}</button>
        <a href="{% url 'client_list' %}" class="btn btn-secondary">{% trans "Back" %}</a>
    {% elif editing %}
        <button type="submit" name="action" value="save" class="btn btn-primary">{% trans "Save" %}</button>
        <a href="{% url 'client_view' client.id %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
    {% elif viewing %}
        <a href="{% url 'client_edit' client.id %}" class="btn btn-primary"
           style="margin-left: 5px">{% trans "Edit" %}</a>
        <a href="{% url 'client_list' %}" class="btn btn-secondary">{% trans "Back" %}</a>
        <button type="button" class="btn btn-danger float-right"
                onclick="showDialogAndEnableRemoveButton()">{% trans "Delete" %}</button>
    {% else %}
        <a href="{% url 'client_list' %}" class="btn btn-secondary">{% trans "Back" %}</a>
    {% endif %}

    <div class="modal fade" id="modalRemove" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Delete customer" %}</h5>
                </div>
                <div class="modal-body">
                    {% trans "Are you sure you want to delete " %} {{ client.name }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"
                            onclick="disableRemoveButton()">{% trans "Cancel" %}</button>
                    <button type="submit" class="btn btn-danger" id="remove_button" value="remove" disabled
                            name="action">{% trans "Delete" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>

client/templates/client/client_new.html
{% extends "base_site.html" %}
{% load i18n staticfiles %}

{% block extrahead %}
    <script src="{% static 'client/js/cep.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">{% trans "New customer" %}</li>
        </ol>

        {% include "client/client.html" %}
    </div>
{% endblock %}

client/templates/client/service_list.html
{% load i18n admin_static %}

<div class="card mb-3">
    <div class="card-header">
        <form method="get">
            <div class="row">
                <div class="col-sm-5 col-12">
                    <input type="text" name="date_min" class="form-control datepicker" id="id_date_0" placeholder="{% trans "Start date" %}">
                </div>
                <div class="col-sm-5 col-12">
                   <input type="text" name="date_max" class="form-control datepicker" id="id_date_1" placeholder="{% trans "End date" %}">
                </div>
                <div class="col-sm-2">
                    <button type="submit" id="search" class="btn btn-primary">{% trans "Search" %}</button>
                </div>
            </div>
        </form>
    </div>
    <form id="form_id" role="form" method="post">{% csrf_token %}
        <div class="card-body">
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                    <div class="row">
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th><input class="form-check" type="checkbox" value="select_all" id="select_all_services"></th>
                                    <th class="w-20">{% trans "Date" %}</th>
                                    <th class="w-20">{% trans "Animal" %}</th>
                                    <th class="w-20">{% trans "Service" %}</th>
                                    <th class="w-15">{% trans "Paid?" %}</th>
                                    <th class="w-20">{% trans "Action" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in services.qs %}
                                    <tr>
                                        <td>
                                            <input type="checkbox" class="checkbox_services form-check" name="services" value="{{ item.id }}" {% if item.payment or item.paid == 'yes' %}disabled{% endif %}>
                                        </td>
                                        <td>{{ item.date }}</td>
                                        <td>{{ item.animal }}</td>
                                        <td>{{ item.service_type }}</td>
                                        <td class="text-center">
                                            {% if item.service_type == 'Exam' and item.service_cost == 0 %}
                                                <em class="fa fa-lg fa-minus-circle" style="color: gray"></em>
                                            {% elif item.paid == 'no' and item.payment %}
                                                {{ item.payment.payment_set.count }} {% trans "of" %} {{ item.payment.installment|make_list|first }}
                                            {% elif item.paid == 'no' %}
                                                <em class="fa fa-lg fa-times-circle" style="color: red"></em>
                                            {% else %}
                                                <em class="fa fa-lg fa-check" style="color: green"></em>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a class="btn btn-warning"
                                                    {% if item.service_type == 'Consultation' %}
                                               href="{% url 'consultation_view' item.id %}"
                                                    {% elif item.service_type == 'Exam' %}
                                               href="{% url 'exam_view' item.id %}"
                                                    {% elif item.service_type == 'Vaccine' %}
                                               href="{% url 'vaccine_view' item.id %}"
                                                    {% else %}
                                               href="#"
                                                    {% endif %} data-toggle="tooltip" data-placement="left" title="{% trans "View service" %}"><em class="fa fa-eye"></em>
                                            </a>
                                            {% if item.payment %}
                                                <a class="btn btn-success" href="{% url 'payment_view' item.payment.id %}" data-toggle="tooltip" data-placement="left" title="{% trans "View payment" %}">
                                                    <em class="fa fa-lg fa-cc-visa"></em>
                                                </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="6" class="text-center">{% trans "No service found!" %}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <button type="submit" name="action" value="pay" class="btn btn-primary">{% trans "Pay now" %}</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>