animal/urls.py
from animal import views
from django.conf.urls import url


urlpatterns = [
    url(r'^search', views.animal_search, name='animal_search'),
    url(r'^select_specie$', views.select_specie_to_filter_breed_and_color, name='select_specie'),
    url(r'^new', views.animal_new, name='animal_new'),
    url(r'^view/(?P<animal_id>\d+)/$', views.animal_view, name='animal_view'),
    url(r'^edit/(?P<animal_id>\d+)/$', views.animal_update, name='animal_edit'),
]

medvet/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from home.views import home, language_change, report


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='custom_user/sign_in.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='custom_user/password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='custom_user/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='custom_user/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='custom_user/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^settings/password/$',
        auth_views.PasswordChangeView.as_view(template_name='custom_user/password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='custom_user/password_change_done.html'),
        name='password_change_done'),

    url(r'^language/(?P<language_code>(?:(?:\w{2})|(?:\w{2}\-\w{2})))$', language_change, name='language_change'),
    url(r'^report/', report, name='report'),
    url(r'^animal/', include('animal.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^custom_user/', include('custom_user.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^service/', include('services.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from services import views
from django.conf.urls import url


urlpatterns = [
    # Consultation
    url(r'^consultation/new/(?P<animal_id>\d+)/$', views.consultation_new, name='consultation_new'),
    url(r'^consultation/list/(?P<animal_id>\d+)/$', views.consultation_list, name='consultation_list'),
    url(r'^consultation/view/(?P<service_ptr_id>\d+)/$', views.consultation_view, name='consultation_view'),
    url(r'^consultation/edit/(?P<service_ptr_id>\d+)/$', views.consultation_update, name='consultation_update'),
    url(r'^consultation/(?P<service_ptr_id>\d+)/animal/(?P<animal_id>\d+)/vaccine/new/$', views.vaccine_new,
        name='vaccine_in_consultation'),
    url(r'^consultation/(?P<service_ptr_id>\d+)/animal/(?P<animal_id>\d+)/exam/new/$', views.exam_new,
        name='exam_in_consultation'),

    # Vaccine
    url(r'^vaccine/new/(?P<animal_id>\d+)/$', views.vaccine_new, name='vaccine_new'),
    url(r'^vaccine/list/(?P<animal_id>\d+)/$', views.vaccine_list, name='vaccine_list'),
    url(r'^vaccine/view/(?P<service_ptr_id>\d+)/$', views.vaccine_view, name='vaccine_view'),
    url(r'^vaccine/edit/(?P<service_ptr_id>\d+)/$', views.vaccine_update, name='vaccine_update'),
    url(r'^vaccine/booster_list', views.vaccine_booster_list, name='vaccine_booster_list'),

    # Exam
    url(r'^exam/new/(?P<animal_id>\d+)/$', views.exam_new, name='exam_new'),
    url(r'^exam/list/(?P<animal_id>\d+)/$', views.exam_list, name='exam_list'),
    url(r'^exam/view/(?P<service_ptr_id>\d+)/$', views.exam_view, name='exam_view'),
    url(r'^exam/edit/(?P<service_ptr_id>\d+)/$', views.exam_update, name='exam_update'),
]

animal/models.py
import datetime
from client.models import Client
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


MALE = 'male'
FEMALE = 'female'
SEX_ANSWER = (
    (MALE, _('Male')),
    (FEMALE, _('Female')),
)

NO = 'no'
YES = 'yes'
YES_NO_ANSWER = (
    (NO, _('No')),
    (YES, _('Yes')),
)

LONG = 'long'
SHORT = 'short'
FUR_ANSWER = (
    (LONG, _('Long')),
    (SHORT, _('Short')),
)


def validate_date_birth(value):
    if value > datetime.date.today():
        raise ValidationError(_('The date of birth can not be greater than the current date.'))


class Specie(models.Model):
    """
    An instance of this class is an animal specie.
    Species registration will be done via Django Admin.

    '__str__'		Returns the name.
    'class Meta'	Sets the description model (singular and plural) and define ordering of data by name.
    """
    name = models.CharField(_('Name'), max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Specie')
        verbose_name_plural = _('Species')
        ordering = ('name', )


class Breed(models.Model):
    """
    An instance of this class is a type of breed.
    Breeds registration will be done via Django Admin.

    '__str__'		Returns the name.
    'class Meta'	Sets the description model (singular and plural) and define ordering of data by name.
    """
    name = models.CharField(_('Name'), max_length=100)
    specie = models.ForeignKey(Specie, verbose_name=_('Specie'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Breed')
        verbose_name_plural = _('Breeds')
        ordering = ('name', )


class Color(models.Model):
    """
    An instance of this class is a type of color for a specific specie.
    Colors registration will be done via Django Admin.

    '__str__'		Returns the name.
    'class Meta'    Sets the description model (singular and plural) and define ordering of data by name.
    """
    name = models.CharField(_('Name'), max_length=100)
    specie = models.ForeignKey(Specie, verbose_name=_('Specie'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Color')
        verbose_name_plural = _('Colors')
        ordering = ('name', )


class Animal(models.Model):
    """
    An instance of this class represents a pet from a customer.

    '__str__'		Returns the name.
    'age'	        Calculates the age according to the date of birth and the current date.
    """
    owner = models.ForeignKey(Client)
    specie = models.ForeignKey(Specie)
    breed = models.ForeignKey(Breed)
    color = models.ForeignKey(Color, blank=True, null=True)
    fur = models.CharField(max_length=5, choices=FUR_ANSWER, blank=True, default=None)
    animal_name = models.CharField(max_length=100)
    birthdate = models.DateField(blank=True, null=True, validators=[validate_date_birth])
    sex = models.CharField(max_length=6, choices=SEX_ANSWER, blank=True)
    spay_neuter = models.CharField(max_length=3, choices=YES_NO_ANSWER, blank=True)
    spay_neuter_date = models.CharField(max_length=100, blank=True)
    microchip = models.CharField(max_length=50, blank=True)
    dead = models.CharField(max_length=3, choices=YES_NO_ANSWER, blank=True, default=NO)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.animal_name

    def age(self):
        if self.birthdate:
            return int((datetime.date.today() - self.birthdate).days / 365)
        else:
            return None

services/models.py
# -*- coding: UTF-8 -*-
import datetime

from django.db import models
from django.db.models import Sum
from django.utils.translation import ugettext_lazy as _

from animal.models import Animal, Specie
from payment.models import PaymentRegister


BODY_CONDITION = (
    ('0', _('1 - Very thin')),
    ('1', _('2 - Underweight')),
    ('2', _('3 - Ideal weight')),
    ('3', _('4 - Overweight')),
    ('4', _('5 - Obese')),
)

DEFAULT_ANSWER = (
    ('normal', _('Normal')),
    ('abnormal', _('Abnormal')),
)

DEHYDRATED_ANSWER = (
    ('no_dehydration', _('No dehydration')),
    ('reports_loss_of_liquids', _('Less than 5% - Reports loss of liquids')),
    ('mild', _('5 to 6% - Mild')),
    ('moderate', _('7 to 9% - Moderate')),
    ('severe', _('10 to 12% - Severe')),
    ('hypovolemic_shock', _('12 to 15% - Hypovolemic shock')),
)

MUCOUS_ANSWER = (
    ('pink', _('Pink')),
    ('blue', _('Blue')),
    ('pale', _('Pale')),
    ('icteric', _('Icteric')),
    ('congested', _('Congested')),
)

EXAM_TYPE = (
    ('collect', _('Exam conducted')),
    ('request', _('Request of exam')),
    ('annex', _('Attach exam')),
)

CONSULTATION = "Consultation"
VACCINE = "Vaccine"
EXAM = "Exam"

NO = 'no'
YES = 'yes'
YES_NO_ANSWER = (
    (NO, _('No')),
    (YES, _('Yes')),
)


class ConsultationType(models.Model):
    """
    An instance of this class is a type of consultation.
    The creation of this instance will be done via Django Admin.

    '__str__'		Returns the name.
    """
    name = models.CharField(max_length=30)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class VaccineType(models.Model):
    """
    An instance of this class is a type of vaccine.
    The creation of this instance will be done via Django Admin.

    '__str__'		Returns the name.
    """
    vaccine_for = models.ForeignKey(Specie, default=1)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class ExamCategory(models.Model):
    """
    An instance of this class is an exam category.
    The creation of this instance will be done via Django Admin.

    '__str__'		Returns the name.
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ExamName(models.Model):
    """
    An instance of this class is a name of an exam.
    The creation of this instance will be done via Django Admin.

    '__str__'		Returns the name.
    """
    category = models.ForeignKey(ExamCategory)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Service(models.Model):
    animal = models.ForeignKey(Animal)
    payment = models.ForeignKey(PaymentRegister, blank=True, null=True)
    service_type = models.CharField(max_length=20)
    date = models.DateField(default=datetime.date.today)
    paid = models.CharField(max_length=3, choices=YES_NO_ANSWER, blank=True, default=NO)
    service_cost = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)


class Consultation(Service):
    consultation_type = models.ForeignKey(ConsultationType)
    title = models.CharField(max_length=255, blank=True)
    temperature = models.CharField(max_length=4, blank=True)
    bodyweight = models.CharField(max_length=10, blank=True)
    body_condition = models.CharField(max_length=1, choices=BODY_CONDITION, blank=True)
    hydration = models.CharField(max_length=25, choices=DEHYDRATED_ANSWER, blank=True)
    mucous_membrane = models.CharField(max_length=10, choices=MUCOUS_ANSWER, blank=True)
    palpable_thyroid = models.CharField(max_length=10, choices=DEFAULT_ANSWER, blank=True)
    palpable_thyroid_note = models.CharField(max_length=255, blank=True)
    auscultation = models.CharField(max_length=10, choices=DEFAULT_ANSWER, blank=True)
    auscultation_note = models.CharField(max_length=255, blank=True)
    abdominal_palpation = models.CharField(max_length=10, choices=DEFAULT_ANSWER, blank=True)
    abdominal_palpation_note = models.CharField(max_length=255, blank=True)
    additional_findings = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self.service_type = CONSULTATION
        self.service_cost = self.consultation_type.price
        super(Service, self).save(*args, **kwargs)


class Vaccine(Service):
    vaccine_type = models.ForeignKey(VaccineType)
    vaccine_in_consultation = models.ForeignKey(Consultation, blank=True, null=True)
    lot = models.CharField(max_length=255, blank=True)
    booster = models.DateField(blank=True, null=True)
    note = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self.service_type = VACCINE
        self.service_cost = self.vaccine_type.price
        super(Service, self).save(*args, **kwargs)


def exam_path(instance, filename):
    return 'exams/{0}/{1}/{2}'.format(
        instance.animal.animal_name, datetime.date.today().strftime('%d-%m-%Y'), str(filename)
    )


class Exam(Service):
    exam_list = models.ManyToManyField(ExamName)
    exam_in_consultation = models.ForeignKey(Consultation, blank=True, null=True)
    exam_type = models.CharField(max_length=10, choices=EXAM_TYPE, default=True)
    exam_file = models.FileField(blank=True, null=True, upload_to=exam_path)
    note = models.TextField(blank=True)

    @property
    def sum_exam(self):
        result = self.exam_list.aggregate(Sum('price'))
        return result['price__sum']

    def save(self, *args, **kwargs):
        self.service_type = EXAM
        if self.exam_type == 'request' or self.exam_type == 'annex':
            self.paid = YES
            self.service_cost = 0
        else:
            self.paid = NO
            self.service_cost = None

        super(Service, self).save(*args, **kwargs)

services/forms.py
import datetime

from django import forms
from django.forms import DateInput, Select, Textarea, TextInput
from django.utils.translation import ugettext_lazy as _

from services.models import Consultation, Exam, Vaccine, VaccineType


class ConsultationForm(forms.ModelForm):

    class Meta:
        model = Consultation
        exclude = ['animal', 'service_type']

        widgets = {
            'consultation_type': Select(attrs={'class': 'form-control'}),
            'title': TextInput(attrs={'class': 'form-control'}),
            'date': DateInput(attrs={'class': 'form-control datepicker', 'required': "",
                                     'data-error': _('This field must be filled.')},),
            'temperature': TextInput(attrs={'class': 'form-control'}),
            'bodyweight': TextInput(attrs={'class': 'form-control'}),
            'body_condition': Select(attrs={'class': 'form-control'}),
            'hydration': Select(attrs={'class': 'form-control'}),
            'mucous_membrane': Select(attrs={'class': 'form-control'}),
            'palpable_thyroid': Select(attrs={'class': 'form-control'}),
            'palpable_thyroid_note': TextInput(attrs={'class': 'form-control'}),
            'auscultation': Select(attrs={'class': 'form-control'}),
            'auscultation_note': TextInput(attrs={'class': 'form-control'}),
            'abdominal_palpation': Select(attrs={'class': 'form-control'}),
            'abdominal_palpation_note': TextInput(attrs={'class': 'form-control'}),
            'additional_findings': Textarea(attrs={'class': 'form-control', 'rows': '4'}),
        }


class VaccineForm(forms.ModelForm):

    booster = forms.DateField(
        input_formats=['%d/%m/%Y'], required=False,
        widget=forms.DateInput(attrs={'class': 'form-control future-datepicker'}, format='%d/%m/%Y')
    )

    class Meta:
        model = Vaccine
        exclude = ['animal', 'service_type', 'vaccine_in_consultation']

        widgets = {
            'date': DateInput(attrs={'class': 'form-control datepicker', 'required': "",
                                     'data-error': _('This field must be filled.')}, ),
            'lot': TextInput(attrs={'class': 'form-control'}),
            'note': Textarea(attrs={'class': 'form-control', 'rows': '4'}),
        }

    def __init__(self, *args, **kwargs):
        super(VaccineForm, self).__init__(*args, **kwargs)
        initial = kwargs.get('initial')
        self.fields['vaccine_type'] = forms.ModelChoiceField(
            queryset=VaccineType.objects.filter(vaccine_for=initial['specie']),
            widget=forms.Select(attrs={'class': 'form-control'})
        )


class ExamForm(forms.ModelForm):

    date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(attrs={'class': 'form-control datepicker'},
                               format='%d/%m/%Y'), initial=datetime.date.today()
    )
    exam_file = forms.FileField(required=False)

    class Meta:
        model = Exam
        exclude = ['animal', 'service_type', 'exam_in_consultation', 'exam_list']

        widgets = {
            'note': Textarea(attrs={'class': 'form-control', 'rows': '4'}),
            'exam_type': Select(attrs={'class': 'form-control'})
        }

services/templates/services/consultation_history.html
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'services/js/remove.js' %}"></script>
{% endblock %}

<div class="card">
    <div class="card-header">
        <div class="float-left"><h5 class="card-title">{% trans "List of consultations" %}</h5></div>
        <div class="float-right"><a href="{% url 'consultation_new' animal.id %}" class="btn btn-primary">{% trans "Create new" %}</a></div>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Type" %}</th>
                    <th class="w-50">{% trans "Info" %}</th>
                    <th>{% trans "Actions" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for item in consultation_list %}
                    <tr>
                        <td>{{ item.date|date:"DATE_FORMAT" }}</td>
                        <td>{{ item.consultation_type }}</td>
                        <td>
                            {% if item.title %}<p><strong>{{ item.title }}</strong></p>{% endif %}
                            {% if item.body_condition %}<p>{% trans "Body condition score" %}: {{ item.get_body_condition_display }}</p>{% endif %}
                            {% if item.temperature %}<p>{% trans "Temperature" %}: {{ item.temperature }}</p>{% endif %}
                            {% if item.bodyweight %}<p>{% trans "Bodyweight" %}: {{ item.bodyweight }}</p>{% endif %}
                            {% if item.mucous_membrane %}<p>{% trans "Respiratory rate" %}: {{ item.get_mucous_membrane_display }}</p>{% endif %}
                            {% if item.hydration %}<p>{% trans "Heart rate" %}: {{ item.get_hydration_display }}</p>{% endif %}
                            {% if item.auscultation == 'abnormal' %}<p>{% trans "Auscultation" %}: {{ item.auscultation_note }}</p>{% endif %}
                            {% if item.palpable_thyroid == 'abnormal' %}<p>{% trans "Palpable thyroid" %}: {{ item.palpable_thyroid_note }}</p>{% endif %}
                            {% if item.abdominal_palpation == 'abnormal' %}<p>{% trans "Abdominal palpation" %}: {{ item.abdominal_palpation_note }}</p>{% endif %}
                            {% if item.additional_findings %}<p>{% trans "Note" %}: {{ item.additional_findings }}</p>{% endif %}
                        </td>
                        <td>
                            <a class="btn btn-warning" href="{% url 'consultation_view' item.id %}" data-toggle="tooltip" data-placement="left" title="{% trans "View consultation" %}"><em class="fa fa-eye"></em></a>
                            <a class="btn btn-success" href="{% url 'consultation_update' item.id %}" data-toggle="tooltip" data-placement="left" title="{% trans "Edit consultation" %}"><em class="fa fa-pencil"></em></a>
                            <a class="btn btn-danger" onclick="show_modal_remove_consultation({{ item.id }});" data-toggle="tooltip" data-placement="left" title="{% trans "Remove consultation" %}"><em class="fa fa-trash-o" style="color:white"></em></a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">{% trans "No consultations found!" %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<form role="form" method="post">{% csrf_token %}
    <div class="modal fade" id="modalRemoveConsultation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Delete consultation" %}</h5>
                </div>
                <div class="modal-body">
                    {% trans "Are you sure you want to delete this consultation?" %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="disableRemoveButton()">{% trans "Cancel" %}</button>
                    <button type="submit" class="btn btn-danger" id="removeConsultation" value="remove-" name="action" disabled>{% trans "Delete" %}</button>
                </div>
            </div>
        </div>
    </div>
</form>

services/templates/services/consultation_view_or_update.html
{% extends "base_site.html" %}
{% load i18n staticfiles %}

{% block content %}
    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'animal_search' %}">{% trans "Animals" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'consultation_list' consultation.animal_id %}">{% trans "Consultations" %}</a></li>
            <li class="breadcrumb-item active">{{ consultation.animal.animal_name }}</li>
        </ol>
        {% include "services/consultation_new.html" %}
    </div>
{% endblock %}

services/templates/services/exam_new.html
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'services/js/exam.js' %}"></script>
{% endblock %}

<form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="row">
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Date" %} <b style="color: red;">*</b></label>
                {{ exam_form.date }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-sm-6 col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Type" %} <b style="color: red;">*</b></label>
                {{ exam_form.exam_type }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-bottom: 10px">
        <div class="col-12">
            <label class="control-label">{% trans "Exams" %} <b style="color: red;">*</b></label>
        </div>
        <div class="col-5">
            <select name="from" id="multiselect" class="form-control" size="8" multiple="multiple"
                    {% if viewing %}disabled{% endif %}>
                {% for exam in exams %}
                    <option value="{{ exam.id }}">{{ exam }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-2 text-center">
            <button type="button" id="multiselect_rightAll" class="btn btn-secondary" style="margin-bottom: 3px"> >> </button><br>
            <button type="button" id="multiselect_rightSelected" class="btn btn-secondary" style="margin-bottom: 3px"> > </button><br>
            <button type="button" id="multiselect_leftSelected" class="btn btn-secondary" style="margin-bottom: 3px"> < </button><br>
            <button type="button" id="multiselect_leftAll" class="btn btn-secondary"> << </button>
        </div>
        <div class="col-5">
            <select name="to" id="multiselect_to" class="form-control" size="8" multiple="multiple"
                    {% if viewing %}disabled{% endif %}>
                {% for exam in exams_selected %}
                    <option value="{{ exam.id }}">{{ exam }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label class="control-label">{% trans "Note" %}</label>
                {{ exam_form.note }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label class="control-label" for="id_exam_file">{% trans "Files" %}</label><br>
                {{ exam_form.exam_file }}
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>

    {% if creating %}
        <button type="submit" name="action" value="save" class="btn btn-primary">{% trans "Save" %}</button>
        {% if consultation %}
            <a href="{% url 'consultation_view' consultation %}" class="btn btn-secondary">{% trans "Back" %}</a>
        {% else %}
            <a href="{% url 'exam_list' animal.id %}" class="btn btn-secondary">{% trans "Back" %}</a>
        {% endif %}
    {% elif editing %}
        <button type="submit" name="action" value="save" class="btn btn-primary">{% trans "Save" %}</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">{% trans "Cancel" %}</a>
    {% elif viewing %}
        <a href="{% url 'client_service_list' exam.animal.owner.id %}" class="btn btn-secondary">{% trans "Back" %}</a>
    {% endif %}
</form>

services/templates/services/exam_pdf.html
{% load i18n staticfiles %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <style type="text/css">
            @page {
                size: a4 portrait;
                margin: 4.5cm 2cm 2cm 2cm;
                padding:0;

                @frame header {
                    -pdf-frame-content:header;
                    top:0.5cm;
                    left:2cm;
                    right:2cm;
                    height:3.5cm;
                }

                @frame footer {
                    -pdf-frame-content:footer;
                    bottom:1cm;
                    left:2cm;
                    right:2cm;
                    height:1cm;
                }
            }
            body {
                all: unset;
                line-height: 10px;
                font-size: 16px;
                text-align: justify;
            }
        </style>
    </head>
    <body>
        <div>
            <div id="header" style="text-align: center">
                {% if images.logo %}
                    <img alt="Logo" src="{{ images.logo.url }}">
                {% endif %}
            </div>
            {% if exam %}
                <br>
                <table width="100%" border="1" cellspacing="0" cellpadding="5">
                    <tr>
                        <td colspan="2" style="background: lightgrey; text-align: center"><strong>{% trans "Animal data" %}</strong></td>
                    </tr>
                    <tr>
                        <td>{% trans "Animal's Name" %}: {{ exam.animal }}</td>
                        <td>{% trans "Specie" %}: {{ exam.animal.specie }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Sex" %}: {{ exam.animal.get_sex_display }}</td>
                        <td>{% trans "Age" %}: {% if exam.animal.age %}{{ exam.animal.age }}{% else %}<em>{% trans "not registered" %}</em>{% endif %}</td>
                    </tr>
                </table>
                <br>
                <p><strong>{% trans "Owner" %}:</strong> {{ exam.animal.owner }}</p>
                <br>
                <p>
                    {% blocktrans %}
                        Dear colleague,<br><br>
                        I ask for the animal mentioned above the following exams:
                    {% endblocktrans %}
                </p>
                <ul>
                    {% for item in exam.exam_list.all %}
                        <li>{{ item }}</li>
                    {% endfor %}
                </ul>
                <br><br><br><br>
                <p>S&atilde;o Paulo, {{ date }}.</p>
                <br><br><br>
                <p style="text-align: center">___________________________________________________</p>
            {% else %}
                {% trans "No exam found." %}
            {% endif %}
        </div>
        <div id="footer" style="text-align: center">
            {% if document.footer %}
                {{ document.footer }}
            {% endif %}
        </div>
    </body>
</html>